//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenbetaDevWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone
    {
        public string Id { get; set; }
        public string additionalFeatures { get; set; }
        public string description { get; set; }
        public string name { get; set; }
    }
}
